name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --verbosity normal

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
    - name: Pack
      run: |
        dotnet restore
        dotnet build -c Release
        dotnet pack ./FSharp.Collections.Builders/FSharp.Collections.Builders.fsproj -c Release --include-symbols
    - name: Publish
      run: dotnet nuget push ./FSharp.Collections.Builders/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
